import { Agent, Lead, Conversation, Appointment, Transaction, LeadStatus, LeadSource } from './types';

export const agents: Agent[] = [
  { id: 'agent-1', name: 'Alex Johnson', avatarUrl: 'https://picsum.photos/seed/1/40/40' },
  { id: 'agent-2', name: 'Maria Garcia', avatarUrl: 'https://picsum.photos/seed/2/40/40' },
  { id: 'agent-3', name: 'James Brown', avatarUrl: 'https://picsum.photos/seed/3/40/40' },
];

export const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'John Doe',
    phone: '+1-555-123-4567',
    source: 'WhatsApp',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Hi, I\'m interested in your services.',
    timestamp: '10:30 AM',
    avatarUrl: 'https://picsum.photos/seed/101/40/40',
  },
  {
    id: 'lead-2',
    name: 'Jane Smith',
    phone: '+1-555-987-6543',
    source: 'Website',
    status: 'In Progress',
    assignedAgent: agents[1],
    lastMessage: 'Can you provide more details about the pricing?',
    timestamp: 'Yesterday',
    avatarUrl: 'https://picsum.photos/seed/102/40/40',
  },
  {
    id: 'lead-3',
    name: 'Peter Jones',
    phone: '+1-555-555-5555',
    source: 'Facebook',
    status: 'Converted',
    assignedAgent: agents[0],
    lastMessage: 'Great, let\'s move forward with the plan.',
    timestamp: '2 days ago',
    avatarUrl: 'https://picsum.photos/seed/103/40/40',
  },
  {
    id: 'lead-4',
    name: 'Sarah Miller',
    phone: '+1-555-111-2222',
    source: 'WhatsApp',
    status: 'Lost',
    assignedAgent: agents[2],
    lastMessage: 'Sorry, I\'m no longer interested.',
    timestamp: '3 days ago',
    avatarUrl: 'https://picsum.photos/seed/104/40/40',
  },
  {
    id: 'lead-5',
    name: 'David Wilson',
    phone: '+1-555-333-4444',
    source: 'Manual',
    status: 'In Progress',
    assignedAgent: agents[1],
    lastMessage: 'Following up on our call last week.',
    timestamp: '4 days ago',
    avatarUrl: 'https://picsum.photos/seed/105/40/40',
  },
  {
    id: 'lead-6',
    name: 'Emily Davis',
    phone: '+1-555-234-5678',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[2],
    lastMessage: 'I have a few questions about feature X.',
    timestamp: '5 days ago',
    avatarUrl: 'https://picsum.photos/seed/106/40/40',
  },
  {
    id: 'lead-7',
    name: 'Michael Brown',
    phone: '+1-555-876-5432',
    source: 'Facebook',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Is there a discount for bulk purchases?',
    timestamp: '5 days ago',
    avatarUrl: 'https://picsum.photos/seed/107/40/40',
  },
  {
    id: 'lead-8',
    name: 'Jessica Taylor',
    phone: '+1-555-432-1098',
    source: 'WhatsApp',
    status: 'In Progress',
    assignedAgent: agents[1],
    lastMessage: 'Checking in on the status of my inquiry.',
    timestamp: '6 days ago',
    avatarUrl: 'https://picsum.photos/seed/108/40/40',
  },
  {
    id: 'lead-9',
    name: 'Chris Martinez',
    phone: '+1-555-654-3210',
    source: 'Manual',
    status: 'Converted',
    assignedAgent: agents[2],
    lastMessage: 'Payment sent. Looking forward to starting.',
    timestamp: '1 week ago',
    avatarUrl: 'https://picsum.photos/seed/109/40/40',
  },
  {
    id: 'lead-10',
    name: 'Amanda Rodriguez',
    phone: '+1-555-789-0123',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'How does your product compare to competitor Y?',
    timestamp: '1 week ago',
    avatarUrl: 'https://picsum.photos/seed/110/40/40',
  },
  {
    id: 'lead-11',
    name: 'Daniel Lewis',
    phone: '+1-555-321-4321',
    source: 'Facebook',
    status: 'Lost',
    assignedAgent: agents[1],
    lastMessage: 'We decided to go with another solution.',
    timestamp: '8 days ago',
    avatarUrl: 'https://picsum.photos/seed/111/40/40',
  },
  {
    id: 'lead-12',
    name: 'Laura Walker',
    phone: '+1-555-432-5432',
    source: 'WhatsApp',
    status: 'In Progress',
    assignedAgent: agents[2],
    lastMessage: 'Thanks for the demo, we will discuss internally.',
    timestamp: '9 days ago',
    avatarUrl: 'https://picsum.photos/seed/112/40/40',
  },
  {
    id: 'lead-13',
    name: 'Kevin Hall',
    phone: '+1-555-543-6543',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Can I get a trial version?',
    timestamp: '10 days ago',
    avatarUrl: 'https://picsum.photos/seed/113/40/40',
  },
  {
    id: 'lead-14',
    name: 'Nancy Allen',
    phone: '+1-555-654-7654',
    source: 'Manual',
    status: 'New',
    assignedAgent: agents[1],
    lastMessage: 'Met at the conference, interested in learning more.',
    timestamp: '11 days ago',
    avatarUrl: 'https://picsum.photos/seed/114/40/40',
  },
  {
    id: 'lead-15',
    name: 'Paul Young',
    phone: '+1-555-765-8765',
    source: 'Facebook',
    status: 'In Progress',
    assignedAgent: agents[2],
    lastMessage: 'The quote seems reasonable. What are the next steps?',
    timestamp: '12 days ago',
    avatarUrl: 'https://picsum.photos/seed/115/40/40',
  },
  {
    id: 'lead-16',
    name: 'Linda King',
    phone: '+1-555-876-9876',
    source: 'WhatsApp',
    status: 'Converted',
    assignedAgent: agents[0],
    lastMessage: 'Everything is set up, thank you for your help!',
    timestamp: '2 weeks ago',
    avatarUrl: 'https://picsum.photos/seed/116/40/40',
  },
  {
    id: 'lead-17',
    name: 'Mark Wright',
    phone: '+1-555-987-0987',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[1],
    lastMessage: 'Just signed up on your website.',
    timestamp: '2 weeks ago',
    avatarUrl: 'https://picsum.photos/seed/117/40/40',
  },
  {
    id: 'lead-18',
    name: 'Betty Scott',
    phone: '+1-555-098-1098',
    source: 'Facebook',
    status: 'In Progress',
    assignedAgent: agents[2],
    lastMessage: 'Could you clarify point 3 in the contract?',
    timestamp: '15 days ago',
    avatarUrl: 'https://picsum.photos/seed/118/40/40',
  },
  {
    id: 'lead-19',
    name: 'Steven Green',
    phone: '+1-555-109-2109',
    source: 'Manual',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Referral from an existing customer.',
    timestamp: '16 days ago',
    avatarUrl: 'https://picsum.photos/seed/119/40/40',
  },
  {
    id: 'lead-20',
    name: 'Karen Adams',
    phone: '+1-555-210-3210',
    source: 'WhatsApp',
    status: 'Lost',
    assignedAgent: agents[1],
    lastMessage: 'The budget was not approved.',
    timestamp: '17 days ago',
    avatarUrl: 'https://picsum.photos/seed/120/40/40',
  },
  {
    id: 'lead-21',
    name: 'George Baker',
    phone: '+1-555-321-4321',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[2],
    lastMessage: 'Interested in a demo.',
    timestamp: '18 days ago',
    avatarUrl: 'https://picsum.photos/seed/121/40/40',
  },
  {
    id: 'lead-22',
    name: 'Donna Nelson',
    phone: '+1-555-432-5432',
    source: 'Facebook',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Commented on our ad for more info.',
    timestamp: '19 days ago',
    avatarUrl: 'https://picsum.photos/seed/122/40/40',
  },
  {
    id: 'lead-23',
    name: 'Frank Carter',
    phone: '+1-555-543-6543',
    source: 'WhatsApp',
    status: 'In Progress',
    assignedAgent: agents[1],
    lastMessage: 'Do you have documentation for the API?',
    timestamp: '20 days ago',
    avatarUrl: 'https://picsum.photos/seed/123/40/40',
  },
  {
    id: 'lead-24',
    name: 'Grace Mitchell',
    phone: '+1-555-654-7654',
    source: 'Manual',
    status: 'New',
    assignedAgent: agents[2],
    lastMessage: 'Walk-in inquiry.',
    timestamp: '3 weeks ago',
    avatarUrl: 'https://picsum.photos/seed/124/40/40',
  },
  {
    id: 'lead-25',
    name: 'Henry Perez',
    phone: '+1-555-765-8765',
    source: 'Website',
    status: 'New',
    assignedAgent: agents[0],
    lastMessage: 'Submitted the contact form on the pricing page.',
    timestamp: '3 weeks ago',
    avatarUrl: 'https://picsum.photos/seed/125/40/40',
  }
];

export const conversations: Conversation[] = [
  {
    lead: leads[0],
    messages: [
      { id: 'msg-1', sender: 'lead', content: 'Hi, I\'m interested in your services.', timestamp: '10:30 AM' },
      { id: 'msg-2', sender: 'system', content: 'Hi John Doe, thanks for contacting us. Our team will respond shortly.', timestamp: '10:31 AM' },
      { id: 'msg-3', sender: 'agent', agent: agents[0], content: 'Hello John! Alex here. I see you\'re interested in our services. How can I help you today?', timestamp: '10:35 AM' },
    ],
  },
  {
    lead: leads[1],
    messages: [
      { id: 'msg-4', sender: 'lead', content: 'Can you provide more details about the pricing?', timestamp: 'Yesterday' },
      { id: 'msg-5', sender: 'system', content: 'Hi Jane Smith, thanks for contacting us. Our team will respond shortly.', timestamp: 'Yesterday' },
    ],
  },
];

export const appointments: Appointment[] = [
  {
    id: 'appt-1',
    clientName: 'Peter Jones',
    date: new Date(new Date().setDate(new Date().getDate() + 2)),
    purpose: 'Onboarding Call',
    assignedAgent: agents[0],
    leadId: 'lead-3',
  },
  {
    id: 'appt-2',
    clientName: 'David Wilson',
    date: new Date(new Date().setDate(new Date().getDate() + 3)),
    purpose: 'Follow-up Discussion',
    assignedAgent: agents[1],
    leadId: 'lead-5',
  },
];

export const transactions: Transaction[] = [
    { id: 'txn-1', date: '2024-07-15', type: 'Income', amount: 1500, description: 'Project Alpha - Phase 1' },
    { id: 'txn-2', date: '2024-07-14', type: 'Expense', amount: 200, description: 'Software Subscription' },
    { id: 'txn-3', date: '2024-07-12', type: 'Income', amount: 750, description: 'Consulting Services' },
    { id: 'txn-4', date: '2024-07-10', type: 'Expense', amount: 50, description: 'Office Supplies' },
];
